### ISSUE TITLE
Always sleeping!

### ISSUE THREAD

**Issue by nikosv** [dado3212/PollDaddyHack#1]
Your script seems like it's been sleeping all the time for 60 seconds.

**Comment by dado3212** [comment]
It does.  It sleeps 60 seconds around every 25 votes.  This is due to how PollDaddy accepts votes.  If you make too many in too short a period of time, it stops registering them.  So when the script registers that it has stopped accepting them, it sleeps.  Is it also printing out the vote statements?  If you want it to go faster, you can decrease the speed it sleeps after each vote (currently 3 seconds). You'll find that if you reduce the 60 seconds of sleep it won't accept them at all.

**Comment by nikosv** [comment]
The thing is it only votes once and then sleeps forever.
![image](https://cloud.githubusercontent.com/assets/1217506/11511777/914aee10-9873-11e5-81d1-bec4b3ccc563.png)

Maybe i am missing something...

**Comment by nikosv** [comment]
What's the redirect var? Should i left it empty?

**Comment by dado3212** [comment]
Can you post the Poll ID and answer id?

**Comment by nikosv** [comment]
poll_id = 9205058
answer_id = "PDI_answer41923139"

**Comment by dado3212** [comment]
Ah.  The problem is that some of the polls disallow voting multiple times from one person.  If you want to get around this, you're going to need a script or program that is constantly changing IP's through proxy, etc.
